-- MySQL Script generated by MySQL Workbench
-- Tue Mar  3 11:45:24 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema management
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema management
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `management` DEFAULT CHARACTER SET utf8 ;
USE `management` ;

-- -----------------------------------------------------
-- Table `management`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `management`.`user` (
  `id` INT NOT NULL,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `roleID` INT NOT NULL,
  PRIMARY KEY (`id`, `roleID`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `management`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `management`.`role` (
  `roleID` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `users` VARCHAR(45) NULL,
  PRIMARY KEY (`roleID`),
  UNIQUE INDEX `id_UNIQUE` (`roleID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `management`.`user_has_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `management`.`user_has_role` (
  `user_id` INT NOT NULL,
  `user_roleID` INT NOT NULL,
  `role_roleID` INT NOT NULL,
  PRIMARY KEY (`user_id`, `user_roleID`, `role_roleID`),
  INDEX `fk_user_has_role_role1_idx` (`role_roleID` ASC) VISIBLE,
  INDEX `fk_user_has_role_user1_idx` (`user_id` ASC, `user_roleID` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_role_user1`
    FOREIGN KEY (`user_id` , `user_roleID`)
    REFERENCES `management`.`user` (`id` , `roleID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_role_role1`
    FOREIGN KEY (`role_roleID`)
    REFERENCES `management`.`role` (`roleID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
